services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: tickets
    ports:
      - 5433:5432
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql